"""Type stubs for the feathertail Rust extension (PyO3 maturin module)."""

from __future__ import annotations

from collections.abc import Callable, Iterator
from typing import Any, Dict, List, Optional, Tuple

# --- Logging / observability ---
def init_logging() -> None: ...
def init_logging_with_config(
    level: str, log_memory: bool, log_performance: bool, log_operations: bool
) -> None: ...
def log_operation(operation: str, details: str) -> None: ...
def log_memory_usage(operation: str, memory_mb: float) -> None: ...
def log_performance(operation: str, duration_ms: float, rows_processed: int) -> None: ...
def log_error(operation: str, error: str, context: Optional[str] = None) -> None: ...
def log_warning(operation: str, warning: str, context: Optional[str] = None) -> None: ...

# --- Debug ---
def enable_debug() -> None: ...
def disable_debug() -> None: ...
def is_debug_enabled() -> bool: ...
def log_debug_info(
    operation: str, duration_ms: float, memory_mb: float, rows_processed: int
) -> None: ...
def log_operation_start(operation: str) -> None: ...
def log_operation_end(operation: str, duration_ms: float) -> None: ...

# --- Profiling ---
def enable_profiling() -> None: ...
def disable_profiling() -> None: ...
def is_profiling_enabled() -> bool: ...
def get_operation_stats(operation: str) -> Optional[Dict[str, float]]: ...
def get_overall_stats() -> Dict[str, float]: ...
def clear_profiling_data() -> None: ...
def print_profiling_report() -> None: ...

class TinyCol:
    @property
    def name(self) -> str: ...
    @property
    def type_str(self) -> str: ...
    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[Any]: ...

class TinyGroupBy:
    keys: List[str]

    def __init__(self, frame: TinyFrame, keys: List[str]) -> None: ...

    def count(self, frame: TinyFrame) -> TinyFrame: ...
    def sum(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def mean(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def min(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def max(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def std(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def var(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def median(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def first(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def last(self, frame: TinyFrame, column: str) -> TinyFrame: ...
    def size(self, frame: TinyFrame) -> TinyFrame: ...

    @property
    def groups(self) -> Dict[Tuple[Any, ...], List[int]]: ...

class TinyFrame:
    """Rust-backed dataframe-like table."""

    # Construction
    def __init__(self) -> None: ...
    @staticmethod
    def from_dicts(records: Any) -> TinyFrame: ...

    # IO / reshape
    def to_dicts(self) -> List[Any]: ...
    def fillna(self, value: Any) -> None: ...
    def cast_column(self, column_name: str, new_type: Any) -> None: ...
    def edit_column(self, column_name: str, func: Callable[..., Any]) -> None: ...
    def drop_columns(self, columns_to_drop: List[str]) -> None: ...
    def rename_column(self, old_name: str, new_name: str) -> None: ...

    # Row ops
    def filter(self, column: str, condition: str, value: Any) -> TinyFrame: ...
    def dropna(self, column: str) -> TinyFrame: ...
    def sort_values(self, by: List[str], ascending: Optional[bool] = None) -> TinyFrame: ...

    def len(self) -> int: ...
    def is_empty(self) -> bool: ...

    @property
    def shape(self) -> Tuple[int, int]: ...
    @property
    def columns(self) -> List[str]: ...

    def __repr__(self) -> str: ...
    def __iter__(self) -> Iterator[Any]: ...

    def col(self, name: str) -> TinyCol: ...

    # Joins
    def inner_join(
        self, other: TinyFrame, left_on: List[str], right_on: List[str]
    ) -> TinyFrame: ...
    def left_join(
        self, other: TinyFrame, left_on: List[str], right_on: List[str]
    ) -> TinyFrame: ...
    def right_join(
        self, other: TinyFrame, left_on: List[str], right_on: List[str]
    ) -> TinyFrame: ...
    def outer_join(
        self, other: TinyFrame, left_on: List[str], right_on: List[str]
    ) -> TinyFrame: ...
    def cross_join(self, other: TinyFrame) -> TinyFrame: ...

    # Stats
    def describe(self) -> TinyFrame: ...
    def corr(self) -> TinyFrame: ...
    def cov(self) -> TinyFrame: ...
    def corr_with(self, column1: str, column2: str) -> float: ...
    def cov_with(self, column1: str, column2: str) -> float: ...
    def skew(self, column: str) -> float: ...
    def kurtosis(self, column: str) -> float: ...
    def quantile(self, column: str, q: float) -> float: ...
    def mode(self, column: str) -> Any: ...
    def nunique(self, column: str) -> int: ...

    # Datetime string columns
    def to_timestamps(self, column: str) -> TinyFrame: ...
    def dt_year(self, column: str) -> TinyFrame: ...
    def dt_month(self, column: str) -> TinyFrame: ...
    def dt_day(self, column: str) -> TinyFrame: ...
    def dt_hour(self, column: str) -> TinyFrame: ...
    def dt_minute(self, column: str) -> TinyFrame: ...
    def dt_second(self, column: str) -> TinyFrame: ...
    def dt_day_of_week(self, column: str) -> TinyFrame: ...
    def dt_day_of_year(self, column: str) -> TinyFrame: ...
    def dt_diff(self, column: str) -> TinyFrame: ...
    def dt_shift(self, column: str, seconds: int) -> TinyFrame: ...

    # Window
    def rolling_mean(self, column: str, window_size: int) -> TinyFrame: ...
    def rolling_sum(self, column: str, window_size: int) -> TinyFrame: ...
    def rolling_std(self, column: str, window_size: int) -> TinyFrame: ...
    def expanding_mean(self, column: str) -> TinyFrame: ...
    def expanding_sum(self, column: str) -> TinyFrame: ...

    # Ranking
    def rank(self, column: str, method: str) -> TinyFrame: ...
    def pct_change(self, column: str) -> TinyFrame: ...

    # Strings
    def str_upper(self, column: str) -> TinyFrame: ...
    def str_lower(self, column: str) -> TinyFrame: ...
    def str_strip(self, column: str) -> TinyFrame: ...
    def str_replace(self, column: str, old: str, new: str) -> TinyFrame: ...
    def str_split(self, column: str, delimiter: str) -> TinyFrame: ...
    def str_contains(self, column: str, substring: str) -> TinyFrame: ...
    def str_len(self, column: str) -> TinyFrame: ...
    def str_cat(self, column: str, separator: str) -> TinyFrame: ...

    # Validation
    def validate_not_null(self, column: str) -> TinyFrame: ...
    def validate_range(
        self, column: str, min: Optional[float] = None, max: Optional[float] = None
    ) -> TinyFrame: ...
    def validate_pattern(self, column: str, pattern: str) -> TinyFrame: ...
    def validate_unique(self, column: str) -> TinyFrame: ...
    def validation_summary(self, column: str) -> Dict[str, float]: ...
