name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Publish with maturin
        uses: PyO3/maturin-action@v1
        with:
          command: publish
          args: --skip-existing
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
