name: Release to PyPI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          path: dist/
          pattern: wheel-*

      - name: List downloaded wheels
        run: |
          echo "Downloaded wheels:"
          find dist/ -name "*.whl" -type f | sort

      - name: Organize wheels for PyPI
        run: |
          # Create a clean dist directory
          mkdir -p dist_clean
          # Copy all wheels to dist_clean with proper names
          find dist/ -name "*.whl" -type f -exec cp {} dist_clean/ \;
          # Remove the old dist directory and rename
          rm -rf dist
          mv dist_clean dist
          echo "Final wheels for PyPI:"
          ls -la dist/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install twine
        run: pip install twine

      - name: Check wheels
        run: |
          twine check dist/*.whl

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
          generate_release_notes: true
          draft: false
          prerelease: false
