name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install maturin
        run: pip install maturin

      - name: Build wheel
        run: maturin build --release

      - name: Install wheel
        run: pip install target/wheels/*.whl

      - name: Install test dependencies
        run: pip install pytest

      - name: Run tests
        run: |
          python -m pytest tests/python/unit/ -v --tb=short

      - name: Test import
        run: |
          python -c "import feathertail as ft; print('Import successful')"
          python -c "import feathertail as ft; data = [{'a': 1, 'b': 2}]; frame = ft.TinyFrame.from_dicts(data); print('Basic functionality works')"
